version: '2.1'
services:
  go:
    build:
      context: ./docker/go
    command: ./scripts/run-all-tests
    environment:
      AWS_ACCESS_KEY_ID:     "AKIzEXAMPLE123456789"
      AWS_SECRET_ACCESS_KEY: "EXAMPLE!SECRET!KEY0123example!secret!key"
      CARPENTER_TEST_S3_BUCKET:   "bucket1"
      CARPENTER_TEST_S3_PREFIX:   "stuff/"
      CARPENTER_TEST_S3_REGION:   "us-east-1"
      CARPENTER_TEST_S3_ENDPOINT: "http://minio:9000"
      GO111MODULE: "on"
    volumes:
     - .:/go/src/github.com/sjansen/carpenter
     - "${GOPATH:-/tmp}/pkg/mod:/go/pkg/mod"
    working_dir: /go/src/github.com/sjansen/carpenter
  minio:
    build:
      context: ./docker/minio
    command: ["server", "/buckets"]
    environment:
      MINIO_ACCESS_KEY: "AKIzEXAMPLE123456789"
      MINIO_SECRET_KEY: "EXAMPLE!SECRET!KEY0123example!secret!key"
